plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'net.copper'
version = '26.2.0'

ext {
    minecraft_version = '26.2'
}

repositories {
    mavenCentral()

    maven {
        name = 'Mojang'
        url = uri('https://libraries.minecraft.net')
    }
}

dependencies {
    // Minecraft itself
    implementation files(
        "libs/minecraft-client-${minecraft_version}.jar",
        "libs/minecraft-common-${minecraft_version}.jar"
    )

    // Copper loader / bytecode tooling
    implementation 'org.ow2.asm:asm:9.8'
    implementation 'org.ow2.asm:asm-tree:9.8'
    implementation "org.slf4j:slf4j-api:2.0.17"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }

    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom {
                name = 'Copper API'
                description = 'The official API for the Copper mod loader'
                url = 'https://github.com/zizogamer0139/Copper.git'

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/license/mit'
                    }
                }

                developers {
                    developer {
                        id = 'zizo'
                        name = 'Zizo'
                    }
                }
            }
        }
    }
}