# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft / Fabric development foundation
minecraft_version=26.2
loom_version=1.17-SNAPSHOT

# Copper
mod_version=26.2.0
maven_group=net.copper

# Fabric API for the initial development environment
fabric_api_version=0.156.0+26.2